// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database';

const SUPABASE_URL = "https://wghcoxcxybumcfetcmev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnaGNveGN4eWJ1bWNmZXRjbWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTQ4OTIsImV4cCI6MjA2MzMzMDg5Mn0.d5UdQVqIpvlJUrwUVeGrQVhdjpcWfZ-eluLT5E8MtcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});